# Generated by Django 2.2.1 on 2020-07-10 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('octo', '0002_octocachestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='octocachestore',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='octocachestore',
            index=models.Index(fields=['hashed'], name='item_hashed'),
        ),
        migrations.AddIndex(
            model_name='octocachestore',
            index=models.Index(fields=['key'], name='item_key'),
        ),
    ]
