# Generated by Django 2.2.1 on 2020-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo', '0003_auto_20200710_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='octocachestore',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
