# Generated by Django 2.2.1 on 2020-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo', '0004_octocachestore_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='octocachestore',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
