# Generated by Django 3.1rc1 on 2020-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo', '0005_auto_20200717_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskmeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=155, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.BinaryField(blank=True, null=True)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('args', models.BinaryField(blank=True, null=True)),
                ('kwargs', models.BinaryField(blank=True, null=True)),
                ('worker', models.CharField(blank=True, max_length=155, null=True)),
                ('retries', models.IntegerField(blank=True, null=True)),
                ('queue', models.CharField(blank=True, max_length=155, null=True)),
            ],
            options={
                'db_table': 'celery_taskmeta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CeleryTasksetmeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskset_id', models.CharField(blank=True, max_length=155, null=True, unique=True)),
                ('result', models.BinaryField(blank=True, null=True)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celery_tasksetmeta',
                'managed': True,
            },
        ),
    ]
