# Generated by Django 2.2.1 on 2019-05-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmdev',
            name='branch_lock',
            field=models.CharField(default='tkn_branch', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='options',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
