# Generated by Django 2.2.1 on 2019-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0002_auto_20190530_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmdev',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
