# Generated by Django 2.2.1 on 2019-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0003_addmdev_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddmDevProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('run_core.addmdev',),
        ),
        migrations.AddField(
            model_name='addmdev',
            name='vm_cluster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addmdev',
            name='vm_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
