# Generated by Django 2.2.1 on 2020-01-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0008_addmcommands_interactive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNamesCorrespond',
        ),
    ]
