# Generated by Django 2.2.1 on 2020-01-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0009_delete_usernamescorrespond'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailsTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_key', models.CharField(max_length=120, unique=True, verbose_name='mail key unique')),
                ('subject', models.CharField(max_length=255, unique=True, verbose_name='mail subject')),
                ('body', models.TextField(blank=True, null=True, verbose_name='mail body')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('private', models.NullBooleanField(verbose_name='private value')),
            ],
            options={
                'db_table': 'octo_mail_texts',
                'managed': True,
            },
        ),
    ]
