# Generated by Django 2.2.1 on 2020-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0010_mailstexts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmdev',
            name='root_pwd',
        ),
        migrations.RemoveField(
            model_name='addmdev',
            name='root_user',
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_ip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mailstexts',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='mailstexts',
            name='mail_key',
            field=models.CharField(max_length=120, unique=True, verbose_name='key unique'),
        ),
        migrations.AlterField(
            model_name='mailstexts',
            name='subject',
            field=models.CharField(max_length=255, unique=True, verbose_name='subject'),
        ),
    ]
