# Generated by Django 2.2.1 on 2020-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0011_auto_20200206_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmdev',
            name='role',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_branch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_full_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_host',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_ip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_owner',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_v_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='addm_v_int',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='branch_lock',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='tideway_pdw',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='tideway_user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='vm_cluster',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addmdev',
            name='vm_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
