# Generated by Django 2.2.1 on 2020-02-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0012_auto_20200206_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmdev',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
