# Generated by Django 2.2.1 on 2020-02-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0013_auto_20200206_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmdev',
            name='addm_branch',
        ),
        migrations.RemoveField(
            model_name='addmdev',
            name='addm_owner',
        ),
        migrations.RemoveField(
            model_name='addmdev',
            name='addm_v_code',
        ),
    ]
