# Generated by Django 2.2.1 on 2020-07-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0016_auto_20200716_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineslog',
            name='user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='serviceslog',
            name='user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
