# Generated by Django 3.1rc1 on 2020-07-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_core', '0019_taskpreparelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesLog',
        ),
    ]
