# Generated by Django 2.2.1 on 2019-11-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTestsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_mode', models.CharField(max_length=50)),
                ('mode_key', models.CharField(max_length=50)),
                ('package_type', models.CharField(max_length=50)),
                ('tku_type', models.CharField(max_length=50)),
                ('tku_build', models.CharField(max_length=50)),
                ('tku_date', models.CharField(max_length=50)),
                ('tku_month', models.CharField(max_length=50)),
                ('upload_test_status', models.CharField(max_length=50)),
                ('upload_test_str_stdout', models.TextField(blank=True, null=True)),
                ('upload_test_str_stderr', models.TextField(blank=True, null=True)),
                ('important_out', models.TextField(blank=True, null=True)),
                ('all_errors', models.TextField(blank=True, null=True)),
                ('all_warnings', models.TextField(blank=True, null=True)),
                ('upload_warnings', models.TextField(blank=True, null=True)),
                ('upload_errors', models.TextField(blank=True, null=True)),
                ('tku_statuses', models.TextField(blank=True, null=True)),
                ('tested_zips', models.TextField(blank=True, null=True)),
                ('addm_name', models.CharField(max_length=50)),
                ('addm_v_int', models.CharField(max_length=50)),
                ('addm_host', models.CharField(max_length=50)),
                ('addm_ip', models.CharField(max_length=50)),
                ('addm_version', models.CharField(max_length=50)),
                ('time_spent_test', models.CharField(max_length=50)),
                ('test_date_time', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'octo_tku_test',
                'managed': True,
                'unique_together': {('mode_key', 'tku_type', 'package_type', 'test_date_time', 'addm_host', 'addm_name')},
            },
        ),
        migrations.CreateModel(
            name='TkuPackagesNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file_path', models.CharField(max_length=255)),
                ('zip_file_name', models.CharField(max_length=255)),
                ('package_type', models.CharField(max_length=50)),
                ('tku_type', models.CharField(max_length=50)),
                ('zip_type', models.CharField(max_length=50)),
                ('addm_version', models.CharField(max_length=50)),
                ('tku_name', models.CharField(max_length=50)),
                ('tku_addm_version', models.CharField(max_length=50)),
                ('tku_build', models.CharField(max_length=50)),
                ('tku_date', models.CharField(max_length=50)),
                ('tku_month', models.CharField(max_length=50)),
                ('tku_pack', models.CharField(max_length=50)),
                ('zip_file_md5_digest', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'octo_tku_packages',
                'managed': True,
                'unique_together': {('zip_file_path', 'package_type', 'addm_version')},
            },
        ),
    ]
