# Generated by Django 2.2.1 on 2020-07-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo_tku_upload', '0002_auto_20191113_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkupackagesnew',
            name='release',
            field=models.CharField(default='release', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadtestsnew',
            name='release',
            field=models.CharField(default='release', max_length=50),
            preserve_default=False,
        ),
    ]
