### Basic authorization.
GET http://127.0.0.1:8000/octo_tku_upload/tku_operations/
Authorization: Basic jenkins rVXoFQSfWZ8er6HdfviT

<> 2021-01-11T104012.200.json

### Simple token
GET http://127.0.0.1:8000/octo_tku_upload/tku_operations/
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f

### Simple token
POST http://127.0.0.1:8000/octo_tku_upload/tku_operations/
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f

### Simple token
POST http://127.0.0.1:8000/octo_tku_upload/tku_operations/
Content-Type: application/json
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f

{
  "operation_key": "jenkins_operations",
  "package_type": "package_type",
  "tku_type": "tku_type"
}

