### Basic authorization.
GET http://127.0.0.1:8000/octo_tku_upload/tku_operations/
Authorization: Basic jenkins rVXoFQSfWZ8er6HdfviT

<> 2021-01-11T104012.200.json

### Simple token
GET http://127.0.0.1:8000/octo_tku_upload/tku_operations/
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f

### Simple token
POST http://127.0.0.1:8000/octo_tku_upload/tku_operations/
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f

### Simple token
POST http://127.0.0.1:8000/octo_tku_upload/tku_operations/
Content-Type: application/json
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f

{
  "operation_key": "jenkins_operations",
  "package_type": "package_type",
  "tku_type": "tku_type"
}

### Jenkins want to run SHIP
POST http://127.0.0.1:8000/octo_tku_upload/tku_operations/?operation_key=jenkins_operations&tku_type=tkn_ship_continuous&package_type=TKN-Release-0000-00-0-227&jenkins_said=IHaveFinished
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f

### Jenking want to run wrong tku_type
POST http://127.0.0.1:8000/octo_tku_upload/tku_operations/?operation_key=jenkins_operations&tku_type=tkn_ship_csdafontinuous&package_type=TKN-Release-0000-00-0-227&jenkins_said=IHaveFinished
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f

### Simple token
POST http://127.0.0.1:8000/octo_tku_upload/tku_operations/?operation_key=upload_test&test_key=TEST_tkn_main_continuous_fresh
Authorization: Token 8142deac287696259f6e21e4d96012eedf165d5f