# Generated by Django 2.2.1 on 2019-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo_tku_patterns', '0002_auto_20191001_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddmDigest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkn_branch', models.CharField(max_length=100)),
                ('addm_host', models.CharField(max_length=100)),
                ('addm_name', models.CharField(max_length=100)),
                ('addm_v_int', models.CharField(max_length=100)),
                ('tests_count', models.CharField(max_length=100)),
                ('patterns_count', models.CharField(max_length=100)),
                ('fails', models.CharField(max_length=100)),
                ('error', models.CharField(max_length=100)),
                ('passed', models.CharField(max_length=100)),
                ('skipped', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'addm_test_digest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestLatestDigestAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('tkn_branch', models.CharField(max_length=255)),
                ('addm_name', models.CharField(max_length=255)),
                ('pattern_library', models.CharField(max_length=255)),
                ('pattern_folder_name', models.CharField(max_length=255)),
                ('time_spent_test', models.FloatField()),
                ('test_date_time', models.DateTimeField()),
                ('addm_v_int', models.CharField(max_length=255)),
                ('change', models.CharField(max_length=255)),
                ('change_user', models.CharField(max_length=255)),
                ('change_review', models.CharField(max_length=255)),
                ('change_ticket', models.CharField(max_length=255)),
                ('change_desc', models.TextField()),
                ('change_time', models.DateTimeField()),
                ('test_case_depot_path', models.CharField(max_length=255)),
                ('test_time_weight', models.CharField(max_length=255)),
                ('test_py_path', models.CharField(max_length=255)),
                ('case_id', models.CharField(max_length=255)),
                ('test_items_prepared', models.IntegerField()),
                ('fails', models.IntegerField()),
                ('error', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('skipped', models.IntegerField()),
            ],
            options={
                'db_table': 'test_latest_digest_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestLatestDigestFailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('tkn_branch', models.CharField(max_length=255)),
                ('addm_name', models.CharField(max_length=255)),
                ('pattern_library', models.CharField(max_length=255)),
                ('pattern_folder_name', models.CharField(max_length=255)),
                ('time_spent_test', models.FloatField()),
                ('test_date_time', models.DateTimeField()),
                ('addm_v_int', models.CharField(max_length=255)),
                ('change', models.CharField(max_length=255)),
                ('change_user', models.CharField(max_length=255)),
                ('change_review', models.CharField(max_length=255)),
                ('change_ticket', models.CharField(max_length=255)),
                ('change_desc', models.TextField()),
                ('change_time', models.DateTimeField()),
                ('test_case_depot_path', models.CharField(max_length=255)),
                ('test_time_weight', models.CharField(max_length=255)),
                ('test_py_path', models.CharField(max_length=255)),
                ('fails', models.IntegerField()),
            ],
            options={
                'db_table': 'test_latest_digest_failed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestLatestDigestPassed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('tkn_branch', models.CharField(max_length=255)),
                ('addm_name', models.CharField(max_length=255)),
                ('pattern_library', models.CharField(max_length=255)),
                ('pattern_folder_name', models.CharField(max_length=255)),
                ('time_spent_test', models.FloatField()),
                ('test_date_time', models.DateTimeField()),
                ('addm_v_int', models.CharField(max_length=255)),
                ('change', models.CharField(max_length=255)),
                ('change_user', models.CharField(max_length=255)),
                ('change_review', models.CharField(max_length=255)),
                ('change_ticket', models.CharField(max_length=255)),
                ('change_desc', models.TextField()),
                ('change_time', models.DateTimeField()),
                ('test_case_depot_path', models.CharField(max_length=255)),
                ('test_time_weight', models.CharField(max_length=255)),
                ('test_py_path', models.CharField(max_length=255)),
                ('test_id', models.CharField(max_length=255)),
                ('case_id', models.CharField(max_length=255)),
                ('test_items_prepared', models.IntegerField()),
                ('passed', models.IntegerField()),
            ],
            options={
                'db_table': 'test_latest_digest_passed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestLatestDigestSkipped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('tkn_branch', models.CharField(max_length=255)),
                ('addm_name', models.CharField(max_length=255)),
                ('pattern_library', models.CharField(max_length=255)),
                ('pattern_folder_name', models.CharField(max_length=255)),
                ('time_spent_test', models.FloatField()),
                ('test_date_time', models.DateTimeField()),
                ('addm_v_int', models.CharField(max_length=255)),
                ('change', models.CharField(max_length=255)),
                ('change_user', models.CharField(max_length=255)),
                ('change_review', models.CharField(max_length=255)),
                ('change_ticket', models.CharField(max_length=255)),
                ('change_desc', models.TextField()),
                ('change_time', models.DateTimeField()),
                ('test_case_depot_path', models.CharField(max_length=255)),
                ('test_time_weight', models.CharField(max_length=255)),
                ('test_py_path', models.CharField(max_length=255)),
                ('test_id', models.CharField(max_length=255)),
                ('case_id', models.CharField(max_length=255)),
                ('test_items_prepared', models.IntegerField()),
                ('skipped', models.IntegerField()),
            ],
            options={
                'db_table': 'test_latest_digest_skipped',
                'managed': False,
            },
        ),
        # migrations.RemoveField(
        #     model_name='testhistory',
        #     name='is_key_pattern',
        # ),
        # migrations.RemoveField(
        #     model_name='testhistory',
        #     name='pattern_file_name',
        # ),
        # migrations.RemoveField(
        #     model_name='testhistory',
        #     name='pattern_file_path',
        # ),
        # migrations.RemoveField(
        #     model_name='testhistory',
        #     name='pattern_file_path_depot',
        # ),
        # migrations.RemoveField(
        #     model_name='testhistory',
        #     name='pattern_folder_path_depot',
        # ),
        # migrations.RemoveField(
        #     model_name='testlast',
        #     name='is_key_pattern',
        # ),
        # migrations.RemoveField(
        #     model_name='testlast',
        #     name='pattern_file_name',
        # ),
        # migrations.RemoveField(
        #     model_name='testlast',
        #     name='pattern_file_path',
        # ),
        # migrations.RemoveField(
        #     model_name='testlast',
        #     name='pattern_file_path_depot',
        # ),
        # migrations.RemoveField(
        #     model_name='testlast',
        #     name='pattern_folder_path_depot',
        # ),
        migrations.AlterField(
            model_name='testcasesdetails',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='addm_host',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='pattern_library',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='test_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='test_py_path',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testlast',
            name='addm_host',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testlast',
            name='pattern_library',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testlast',
            name='test_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testlast',
            name='test_py_path',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='testcases',
            index=models.Index(fields=['test_py_path'], name='case_test_py_path'),
        ),
        migrations.AddIndex(
            model_name='testcases',
            index=models.Index(fields=['change_time'], name='case_change_time'),
        ),
        migrations.AddIndex(
            model_name='testcases',
            index=models.Index(fields=['tkn_branch', 'pattern_library', 'pattern_folder_name'], name='case_unique'),
        ),
        migrations.AddIndex(
            model_name='testhistory',
            index=models.Index(fields=['test_py_path'], name='test_history_test_py_path'),
        ),
        migrations.AddIndex(
            model_name='testhistory',
            index=models.Index(fields=['test_date_time'], name='test_history_date_time'),
        ),
        migrations.AddIndex(
            model_name='testhistory',
            index=models.Index(fields=['tkn_branch', 'pattern_library', 'pattern_folder_name', 'tst_name', 'tst_class', 'addm_name'], name='test_history_test_unique'),
        ),
        migrations.AddIndex(
            model_name='testlast',
            index=models.Index(fields=['test_py_path'], name='test_last_test_py_path'),
        ),
        migrations.AddIndex(
            model_name='testlast',
            index=models.Index(fields=['test_date_time'], name='test_last_date_time'),
        ),
        migrations.AddIndex(
            model_name='testlast',
            index=models.Index(fields=['tkn_branch', 'pattern_library', 'pattern_folder_name', 'tst_name', 'tst_class', 'addm_name'], name='test_last_test_unique'),
        ),
    ]
