# Generated by Django 2.2.1 on 2020-01-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo_tku_patterns', '0003_auto_20191214_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHistoryDigestDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('tkn_branch', models.CharField(max_length=255)),
                ('addm_name', models.CharField(max_length=255)),
                ('pattern_library', models.CharField(max_length=255)),
                ('pattern_folder_name', models.CharField(max_length=255)),
                ('time_spent_test', models.FloatField()),
                ('test_date_time', models.DateTimeField()),
                ('addm_v_int', models.CharField(max_length=255)),
                ('change', models.CharField(max_length=255)),
                ('change_user', models.CharField(max_length=255)),
                ('change_review', models.CharField(max_length=255)),
                ('change_ticket', models.CharField(max_length=255)),
                ('change_desc', models.TextField()),
                ('change_time', models.DateTimeField()),
                ('test_case_depot_path', models.CharField(max_length=255)),
                ('test_time_weight', models.CharField(max_length=255)),
                ('test_py_path', models.CharField(max_length=255)),
                ('case_id', models.CharField(max_length=255)),
                ('test_items_prepared', models.IntegerField()),
                ('fails', models.IntegerField()),
                ('error', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('skipped', models.IntegerField()),
            ],
            options={
                'db_table': 'test_history_digest_daily',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='fail_class',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='fail_module',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='fail_name',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='fail_status',
        ),
        migrations.RemoveField(
            model_name='testlast',
            name='fail_class',
        ),
        migrations.RemoveField(
            model_name='testlast',
            name='fail_module',
        ),
        migrations.RemoveField(
            model_name='testlast',
            name='fail_name',
        ),
        migrations.RemoveField(
            model_name='testlast',
            name='fail_status',
        ),
        migrations.AlterField(
            model_name='testlast',
            name='time_spent_test',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
