# Generated by Django 2.2.1 on 2020-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo_tku_patterns', '0004_auto_20200113_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistory',
            name='time_spent_test',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
