# Generated by Django 2.2.1 on 2020-01-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo_tku_patterns', '0005_auto_20200113_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='test_time_weight',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
