# Generated by Django 2.2.1 on 2020-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo_tku_patterns', '0006_auto_20200113_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistory',
            name='pattern_folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='pattern_library',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testlast',
            name='pattern_folder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testlast',
            name='pattern_library',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
