# Generated by Django 2.2.1 on 2020-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octo_tku_patterns', '0007_auto_20200611_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='test_case_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testlast',
            name='test_case_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
