# Generated by Django 2.2.1 on 2019-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [

        migrations.RemoveField(
            model_name='testhistory',
            name='is_key_pattern',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='pattern_file_name',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='pattern_file_path',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='pattern_file_path_depot',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='pattern_folder_path_depot',
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='addm_host',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='pattern_library',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='test_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='test_py_path',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='testhistory',
            index=models.Index(fields=['test_py_path'], name='test_history_test_py_path'),
        ),
        migrations.AddIndex(
            model_name='testhistory',
            index=models.Index(fields=['test_date_time'], name='test_history_date_time'),
        ),
        migrations.AddIndex(
            model_name='testhistory',
            index=models.Index(
                fields=['tkn_branch', 'pattern_library', 'pattern_folder_name', 'tst_name', 'tst_class', 'addm_name'],
                name='test_history_test_unique'),
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='fail_class',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='fail_module',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='fail_name',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='fail_status',
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='time_spent_test',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
